### ISSUE TITLE
Error when retrieving events

### ISSUE THREAD

**Issue by ManuelFrigerio** [whereisciao/eventbrite#8]
Hi,

I'm experiencing a weird problem.

Here's what I do:
- I correctly obtain a user oAuth using EventBrite oAuth gem
- I correctly create an instance of the EventBrite class:
  `eventbrite = Eventbrite::REST::Client.new(oauth_token: user.oath_token)`
- I try to retrieve all the events for that specific user:
  `events = eventbrite.user_owned_events("me", status:"all")`

This is when I get this error:
`Eventbrite::Error::BadRequest: You passed an invalid page number`

And this is the complete trace:

`#<Eventbrite::Cursor:0x007fe55aaf5950 @key=:events, @klass=Eventbrite::Event, @client=#<Eventbrite::REST::Client:0x007fe554ad5250 @oauth_token="63N36IWHGLWJZNNWNWT5", @middleware=#<Faraday::RackBuilder:0x007fe554add8d8 @handlers=[Faraday::Request::Multipart, Faraday::Request::UrlEncoded, Eventbrite::REST::Response::RaiseError, Eventbrite::REST::Response::ParseJson, Faraday::Adapter::NetHttp], @app=#<Faraday::Request::Multipart:0x007fe55a42f6c0 @app=#<Faraday::Request::UrlEncoded:0x007fe55a42f7b0 @app=#<Eventbrite::REST::Response::RaiseError:0x007fe55a42f878 @app=#<Eventbrite::REST::Response::ParseJson:0x007fe55a42f918 @app=#<Faraday::Adapter::NetHttp:0x007fe55a42fa08 @app=#<Proc:0x007fe55a42fb70@/Users/xyz/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:152 (lambda)>>>>>>>, @user_agent="Eventbrite Ruby Gem 0.11.0", @connection_options={:builder=>#<Faraday::RackBuilder:0x007fe554add8d8 @handlers=[Faraday::Request::Multipart, Faraday::Request::UrlEncoded, Eventbrite::REST::Response::RaiseError, Eventbrite::REST::Response::ParseJson, Faraday::Adapter::NetHttp], @app=#<Faraday::Request::Multipart:0x007fe55a42f6c0 @app=#<Faraday::Request::UrlEncoded:0x007fe55a42f7b0 @app=#<Eventbrite::REST::Response::RaiseError:0x007fe55a42f878 @app=#<Eventbrite::REST::Response::ParseJson:0x007fe55a42f918 @app=#<Faraday::Adapter::NetHttp:0x007fe55a42fa08 @app=#<Proc:0x007fe55a42fb70@/Users/xyz/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:152 (lambda)>>>>>>>, :headers=>{:accept=>"application/json", :user_agent=>"Eventbrite Ruby Gem 0.11.0"}, :request=>{:open_timeout=>10, :timeout=>30}}, @connection_v3=#<Faraday::Connection:0x007fe554adcbe0 @parallel_manager=nil, @headers={"Accept"=>"application/json", "User-Agent"=>"Eventbrite Ruby Gem 0.11.0"}, @params={}, @options=#<Faraday::RequestOptions timeout=30, open_timeout=10>, @ssl=#<Faraday::SSLOptions verify=true>, @default_parallel_manager=nil, @builder=#<Faraday::RackBuilder:0x007fe554add8d8 @handlers=[Faraday::Request::Multipart, Faraday::Request::UrlEncoded, Eventbrite::REST::Response::RaiseError, Eventbrite::REST::Response::ParseJson, Faraday::Adapter::NetHttp], @app=#<Faraday::Request::Multipart:0x007fe55a42f6c0 @app=#<Faraday::Request::UrlEncoded:0x007fe55a42f7b0 @app=#<Eventbrite::REST::Response::RaiseError:0x007fe55a42f878 @app=#<Eventbrite::REST::Response::ParseJson:0x007fe55a42f918 @app=#<Faraday::Adapter::NetHttp:0x007fe55a42fa08 @app=#<Proc:0x007fe55a42fb70@/Users/xyz/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:152 (lambda)>>>>>>>, @url_prefix=#<URI::HTTPS https://www.eventbriteapi.com/>, @proxy=nil>>, @request_method=:get, @path="/v3/users/me/owned_events/", @options={:status=>"all", :page=>1}, @version=:v3, @collection=[], @attrs={:pagination=>{:object_count=>0, :page_number=>1, :page_size=>50, :page_count=>0}, :events=>[]}>`

The weirdness comes from the fact that it works ok with some users and it raises this error with others.

Just for reference, both type of users have multiple events, past and present.

Thanks in advance!

**Comment by whereisciao** [comment]
@ManuelFrigerio Do you know if all the events have been fetched before the error happens?

**Comment by ManuelFrigerio** [comment]
@whereisciao not sure what you mean.. but from what I can understand no events has been fetched at all. Eventbrite told me that this error happens when someone passes a number in the page parameter that exceeds the number of pages available.

Any thoughts?

**Comment by whereisciao** [comment]
@ManuelFrigerio -- My bet is the gem is miscounting. What tricks me up is it works for some users and not others. My current plan is to update the code to catch the error, then return the events collected thus far.

**Comment by whereisciao** [comment]
@ManuelFrigerio -- I need more information before I am able to determine a good solution. I understand you are just getting events with this syntax:

`events = eventbrite.user_owned_events("me", status:"all")`.

The statement above will returns an `Eventbrite::Cursor` object with an initial set of event objects. A `.all` or a block will be called in order to actually go through the pagination. 

What I am concerned about is the users that are failing don't own any events. For the events that don't work, have you tried using https://www.eventbriteapi.com to run the call manually? The information I need is the pagination.

**Comment by whereisciao** [comment]
@ManuelFrigerio I've cut a branch to see if I can handle the event the error occurs on the first page. Can you see if this fixes your issue? 

To test, clone the code to your repository. There is a `console` that you can invoke to run the gem in IRB.

https://github.com/whereisciao/eventbrite/commit/e0dd9075b0e5bbd2f371874c7dee20b200aa7270
